### PR TITLE
Sanitize xml check + Catkin Workspace Directory Check

### PR DESCRIPTION
**Pull request by aorthey**
I was running into two problems using the sdf2urdf parser:

(1) if an xml file used tags like that:
< parent >
    linkname
< / parent >
then the linkname was copied >including< the whitespaces before and after into a variable. So the script only worked for cases where the format was < parent >linkname< / parent >. I wrote a small function to sanitize this input, such that trailing whitespaces are removed
(2) if the workspace directory of catkin is not /catkin_ws/src, then the script fails without any explicit comments. I added a small function to check if the catkin workspace exists, and let the user change the directory on the fly if necessary.

Might be useful for people running into a similar problem.

### CODE REVIEW

**Comment by andreasBihlmaier** [comment]
Hi orthez,

thanks for the bug report and your suggested fixes.

I fully agree with your changes expect the interactive part (https://github.com/andreasBihlmaier/pysdf/pull/2/files#diff-68af4b20c186453f0ec4b3c06f66fba0R25). Please change this to failure exit with a respective error message.
Also change the sys.exit(0) to sys.exit(1) for the failure cases.

Furthermore, please remove the debug output https://github.com/andreasBihlmaier/pysdf/pull/2/files#diff-68af4b20c186453f0ec4b3c06f66fba0R40 and https://github.com/andreasBihlmaier/pysdf/pull/2/files#diff-68af4b20c186453f0ec4b3c06f66fba0R42.

I will test and merge the changes then.

**Comment by aorthey** [comment]
Hello Andreas,

thanks for the input. i fixed the code according to your comments.

**Comment by andreasBihlmaier** [comment]
Fine otherwise :)

**Comment by aorthey** [comment]
Ok thanks for spotting that mistake, i changed it to if.

**Pull request merged**
